pub static WORDS: &[&str] = &[
    "able", "about", "above", "actor", "adapt", "ahead", "alarm", "album", "alert", "alone",
    "alpha", "amber", "angel", "apple", "arena", "argon", "arrow", "asset", "atlas", "audio",
    "basic", "beach", "beacon", "begin", "bench", "binary", "blade", "blaze", "block", "bloom",
    "bonus", "bravo", "brick", "brief", "broad", "cabin", "cable", "candy", "cargo", "catch",
    "cause", "charm", "chess", "chief", "civic", "clean", "clock", "cloud", "codec", "color",
    "comet", "crate", "crest", "crisp", "cross", "crown", "curve", "cycle", "delta", "depth",
    "digit", "drama", "drift", "eager", "earth", "echo", "edge", "elbow", "elite", "ember",
    "empty", "enter", "equal", "error", "event", "exact", "extra", "faith", "field", "final",
    "flame", "flash", "fleet", "focus", "frame", "fresh", "front", "frost", "gamma", "giant",
    "glide", "globe", "glory", "grace", "grant", "guard", "guest", "guide", "habit", "happy",
    "haven", "heart", "heavy", "honey", "humor", "image", "index", "input", "issue", "ivory",
    "jelly", "joint", "judge", "jumpy", "karma", "knife", "knock", "label", "laser", "level",
    "light", "limit", "logic", "lucky", "lunar", "magic", "major", "maker", "march", "match",
    "metal", "micro", "minor", "model", "motor", "mount", "music", "noble", "north", "novel",
    "oasis", "ocean", "offer", "omega", "orbit", "order", "other", "panel", "party", "pause",
    "peace", "phase", "photo", "piano", "pilot", "pixel", "plain", "plane", "plant", "pulse",
    "quick", "quiet", "rally", "rapid", "ratio", "ready", "rebel", "relay", "renew", "reply",
    "rider", "right", "river", "robot", "rough", "round", "route", "royal", "scale", "scene",
    "scope", "score", "screen", "sense", "serve", "shade", "shift", "shore", "sight", "skill",
    "smart", "solid", "sound", "south", "space", "spark", "speed", "spice", "spike", "spoon",
    "stack", "stage", "star", "start", "steam", "stone", "storm", "story", "style", "sugar",
    "swift", "swing", "table", "tactic", "tempo", "tensor", "theme", "thick", "thing", "think",
    "tower", "trace", "track", "trade", "trend", "tribe", "trick", "trust", "ultra", "union",
    "unity", "value", "vapor", "vivid", "voice", "voter", "watch", "water", "wheel", "wired",
    "wiser", "woman", "world", "worth", "yield", "young", "zebra", "zesty", "zonal",
];

pub static BONUS_WORDS: &[&str] = &[
    "afterburner",
    "constellation",
    "headquarters",
    "imagination",
    "lightweight",
    "microgravity",
    "observatory",
    "performance",
    "resilience",
    "spectacular",
    "teleporter",
    "transmitter",
    "university",
    "waterfall",
];

pub static WORDLE_WORDS: &[&str] = &[
    "able", "acid", "acorn", "after", "album", "alert", "alien", "alpha", "angel", "apple",
    "arrow", "asset", "audio", "bacon", "basic", "beacon", "berry", "blaze", "bloom", "bravo",
    "brick", "broad", "cabin", "cargo", "cause", "chain", "charm", "chess", "civic", "clean",
    "clock", "cloud", "comet", "copper", "crown", "curve", "delta", "drift", "eagle", "earth",
    "ember", "entry", "equal", "fable", "faith", "flame", "flash", "fleet", "focus", "frame",
    "fresh", "front", "frost", "galaxy", "giant", "glide", "globe", "grace", "grant", "guard",
    "habit", "haven", "heart", "honey", "index", "input", "issue", "ivory", "jelly", "joint",
    "judge", "karma", "laser", "light", "limit", "logic", "lunar", "magic", "maker", "major",
    "metal", "minor", "model", "mount", "music", "north", "oasis", "ocean", "orbit", "order",
    "panel", "party", "phase", "pilot", "pixel", "plain", "plane", "plant", "pulse", "quick",
    "quiet", "rally", "rapid", "ratio", "ready", "rebel", "relay", "renew", "reply", "river",
    "robot", "rough", "route", "royal", "scale", "scene", "scope", "score", "shade", "shift",
    "shore", "sight", "skill", "solid", "sound", "south", "space", "spark", "speed", "spice",
    "spike", "stack", "stage", "star", "start", "steam", "stone", "storm", "story", "style",
    "sugar", "swift", "table", "tactic", "tempo", "theme", "tower", "trace", "track", "trade",
    "trend", "tribe", "trick", "trust", "union", "unity", "value", "vapor", "vivid", "voice",
    "watch", "water", "wheel", "wired", "world", "worth", "yield", "young",
    "battery", "blanket", "browser", "capture", "carrier", "central", "chamber", "channel",
    "chisel", "cluster", "command", "compose", "concert", "convert", "crystal", "default",
    "diamond", "display", "dynamic", "element", "factory", "feature", "freedom", "gateway",
    "genuine", "gravity", "harvest", "heading", "imagine", "inspect", "journal", "journey",
    "lantern", "machine", "minimal", "monitor", "morning", "mystery", "network", "october",
    "offload", "palette", "passage", "pattern", "percent", "picture", "pioneer", "process",
    "project", "quality", "railway", "receiver", "refresh", "release", "resource", "science",
    "silence", "station", "storage", "summary", "texture", "thought", "torrent", "traffic",
    "upgrade", "utility", "virtual", "visitor", "warning", "weather", "whisper", "windows",
    "workshop", "zigzag",
    "amplitude", "broadband", "dashboard", "education", "flightplan", "framework", "keyboard",
    "landscape", "lighthouse", "magnitude", "objective", "overdrive", "processor", "prototype",
    "reference", "signature", "telescope", "treatment", "warehouse", "wilderness",
];
